name: Publish to GH Pages
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.64.0"

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: anisuzzamanbabla/anisuzzamanbabla.github.io
          publish_dir: ./public
          #   keep_files: true
          git config user.name 'anisuzzamanbabla'
          git config user.email 'anisuzzamanbabla@gmail.com'
          publish_branch: gh-pages
        #   cname: example.coms